server:
  port: 8089 # tomcat端口号
  servlet:
    context-path: /springboot # 项目根路径
spring:
  #datasource:
    #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    #username: oms
    #password: pass
    #driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    prefix: classpath:/templates/

  redis:
    host: 192.168.209.125
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 30000
        max-idle: 8
        min-idle: 0
    connect-timeout: 3000
    database: 16
    password: 123456 #redis数据库索引
  application:
    name: sentinel-boot
  cloud:
    sentinel:
      transport:
        port: localhost:9000




